apiVersion: v1
kind: Pod
metadata:
  name: cardapio
  namespace: playground
spec:
  containers:
    - name: cardapio-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: cardapio-config
  restartPolicy: Never
