apiVersion: v1
kind: Pod
metadata:
  name: cardapio
  namespace: playground
spec:
  containers:
    - name: cardapio-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", 'while [ "${loop_controle}" = "y" ] ; do echo "A melhor comida é ${melhorcomida}, mas infelizmente só estou podendo comer ${comidapermitida}...." ; done' ]
      envFrom:
      - configMapRef:
          name: cardapio-config
  restartPolicy: Never
