apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
  namespace: playground
spec:
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
         - "bin/bash"
         - "-c"
         - "for i in `seq 20`; do echo $i ; sleep 3s ; done"
      restartPolicy: Never
