apiVersion: v1
kind: Pod
metadata:
  name: checa-credencial
  namespace: playground
spec:
  containers:
    - name: checa-credencial-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", 'echo "Eu sou o `cat /etc/secretdb/username`, e minha chave de acesso é `cat /etc/secretdb/password`...."' ]
      volumeMounts:
      - name: secretdb
        mountPath: "/etc/secretdb"
        readOnly: true
  restartPolicy: Never
  volumes:
  - name: secretdb
    secret:
      secretName: authcredential
