# eks_cluster.yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-de-k-a-s
  region: us-east-1

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t2.medium
    minSize: 2
    maxSize: 10
    desiredCapacity: 5
    volumeSize: 20
    labels: {role: worker}
    tags:
      nodegroup-role: worker
