# eks_cluster.yaml
# Um cluster com um managed nodegroup
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-de-k-a-s
  region: us-east-1

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t2.medium
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    labels: {role: worker}
    tags:
      nodegroup-role: worker

  - name: managed-ng-2
    instanceType: t2.medium
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    labels: {role: db}
    tags:
      nodegroup-role: db
